# Generated by Django 3.2 on 2024-01-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_producer", "0002_alter_order_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="User",
            new_name="user",
        ),
    ]
