# Generated by Django 3.2 on 2024-01-26 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_producer", "0003_rename_user_order_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="regular_price",
        ),
    ]
