# Generated by Django 3.2 on 2024-01-28 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("data_producer", "0005_auto_20240127_0219"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("result", models.CharField(max_length=255)),
            ],
        ),
    ]
